### ISSUE TITLE
message clashes with base R

### ISSUE THREAD

**Issue by sanjmeh** [r-lib/gmailr#163]
I understand `gmailr::message()` is deprecated but still presents a name space clash with base R `message()`. The following error is encountered, which is unavoidable and inevitable as name space clash will always happen with base R.

```
Auto-refreshing stale OAuth token.
Error in gmailr_GET(c("messages", id), user_id, class = "gmail_message",  : 
  Gmail API error: 400
  Invalid id value
In addition: Warning message:
`message()` was deprecated in gmailr 1.0.0.
Please use `gm_message()` instead. 
```

**Comment by jennybc** [comment]
I think/hope that the warning you saw was due to an internal use of `gmailr::message()`, which has since been removed. I can't find any current, internal uses of it.

If this is still a problem, please open a new issue with code I can run to trigger the warning. I am advancing the deprecation process in the next release, so we can remove these clashing functions entirely in the future.
